version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_rest_with_spring_boot
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_with_spring_boot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
